### ISSUE TITLE
Zeroizing SecretKey

### ISSUE THREAD

**Issue by lann** [jedisct1/rust-ed25519-compact#11]
I believe it is currently impossible to safely zeroize `SecretKey` since you cannot get mutable access to the underlying array. I'd be happy to write a PR doing one of these, any of which would allow zeroization:

- Impl [`zeroize::Zeroize`](https://docs.rs/zeroize/latest/zeroize/trait.Zeroize.html) on `SecretKey` (perhaps behind a feature flag)
- Impl `DerefMut` on `SecretKey`
- Add `SecretKey::into_inner(self) -> [u8; SecretKey::BYTES]`

**Comment by jedisct1** [comment]
We already have `Deref`, we can totally add `DerefMut` :)
