### ISSUE TITLE
Formal verification report link

### ISSUE THREAD

**Issue by pinkforest** [jedisct1/rust-ed25519-compact#13]
Hi @jedisct1

The crate README.md says there is Formal verification -

Re: https://github.com/The-DevX-Initiative/RCIG_Coordination_Repo/blob/main/Awesome_Rust_Cryptography.md

I'm sending a PR there - do we have a link to the formal verification report we can refer to please ?

Cheers

**Comment by jedisct1** [comment]
The [code](https://github.com/jedisct1/rust-ed25519-compact/blob/master/src/curve25519.rs) for field arithmetic is generated with [fiat-crypto](https://github.com/mit-plv/fiat-crypto).
