### ISSUE TITLE
Feature-change for `>= 1.0.13` regarding `signatures` imports

### ISSUE THREAD

**Issue by brycx** [jedisct1/rust-ed25519-compact#15]
This is not a bug per se. I'm not even entirely sure what the correct action is in this case, but I thought I'd mention it anyway. With versions `1.0.13` and onward, a new feature `signatures` was introduced. AFAIU, this constitutes a minor SemVer version bump, according to [API Evolution RFC](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md). I'd have though this would require a `1.1.x` version, instead.

Feel free to close this @jedisct1, if this was intentional.

In case anyone else had their `ed25519-compact` on non-default-features, pulled in signature-related types and their build broke: this can be fixed by adding `"signatures"` to selected features of this crate.

**Comment by jedisct1** [comment]
Oh, indeed, thanks!

I guess a better way would be to have a "disable-signatures" feature instead.

**Comment by brycx** [comment]
> I guess a better way would be to have a "disable-signatures" feature instead.

In terms of backward compatibility, yes. But the way the remaining features are structured now, it'd be a bit awkward. Then the "enable only what you want" wouldn't apply to signatures, but just the rest.

**Comment by jedisct1** [comment]
Backward compatibility feels more important.

To some extent `opt_size` also removes something.

Version 1.0.15 was released to fix this.

Thanks!
