### ISSUE TITLE
Feature request: Add `Drop` impl and `DerefMut` for all `PublicKey` types

### ISSUE THREAD

**Issue by poliorcetics** [jedisct1/rust-ed25519-compact#21]
While `PublicKeys` are, by definition, public, and leaking them is not that dangerous in theory, in practice finding where a public key is in memory can help find where crypto code is situated more easily and watch for it. It can also confirm which type of crypto is used based on the key length and format.

I'm happy to implement it if you would accept such a feature.

Implementing `Drop` would need a `3.0.0` because `PublicKey`s are `Copy` at the moment. Implementing `DerefMut` would not, so we could do that in as a first helper ?

**Comment by jedisct1** [comment]
The algorithm is not a secret. Kerckhoffs's principle.

Public keys here are just 32 random-looking bytes. The crypto code is already trivial to locate by searching for constants such as the base point coordinates and the field size.
