### ISSUE TITLE
very long compile time when targeting WASM

### ISSUE THREAD

**Issue by thomasheyenbrock** [jedisct1/rust-ed25519-compact#22]
Hello 👋 this is more of a question: When targeting WASM and including full debug info, building this package is taking multiple minutes. Is there any chance this can be speed up?

To reproduce, running the following takes 3min 20sec on my MacBook Pro M1 Max:

```sh
cargo rustc --release --target wasm32-wasi -- -g
```

**Comment by thomasheyenbrock** [comment]
Hey @jedisct1 👋 did anything happen that makes this obsolete? I'm still observing very long build times on the latest master. To emphasize, this is more of a _question_ and not really an issue in the sense that something is not working 🤔 (Lmk if there's a better place to ask about this!)

**Comment by jedisct1** [comment]
@thomasheyenbrock Nothing, since no one reported this to the Rust project. This is a bug in the Rust compiler, so that would be a better place to report it.

It seems to be in the way it generates debugging symbols. Removing `-g` doesn't exhibit this.
