### ISSUE TITLE
pem feature for no_std?

### ISSUE THREAD

**Issue by RaitoBezarius** [jedisct1/rust-ed25519-compact#25]
Hi there, thank you a lot for the amazing library!

I'm trying to use it in a no_std context with the pem feature, which I think, can work with no_std as ct-codecs is no_std.
But due to Cargo limitations, I cannot pass no_std request to the subdependency in the project.

Is there a way to reflect the no_std for pem feature in this project?

Thank you a lot!

**Comment by jedisct1** [comment]
Serialization functions return `Vec` and `String` values, so that wouldn't work with `no_std`.

Supporting `no_std` for these would imply implementing a second, completely different API to do the same thing (taking mutable slices, and returning sub-slices). That'd be a bit ugly and painful to maintain.

I'd rather avoid this. However, the `pem.rs` file is pretty much self-contained, so it can be turned into a dedicated crate, with a `no_std` compatible API.

**Comment by tarcieri** [comment]
FWIW, the @RustCrypto `pem-rfc7468` crate has full heapless `no_std` support build on a constant-time Base64 codec, implemented side-by-side with the allocating APIs.

It also supports on-the-fly Base64 decoding/encoding in constant time, which eliminates the need to perform a first pass to decode/encode to DER, allowing the DER to be parsed directly from or encoded to PEM without an intermediate buffer.

The `pkcs8` crate is already built on it, as it were (although it doesn't fully support the on-the-fly PEM APIs yet).

**Comment by RaitoBezarius** [comment]
> Serialization functions return `Vec` and `String` values, so that wouldn't work with `no_std`.
> 
> Supporting `no_std` for these would imply implementing a second, completely different API to do the same thing (taking mutable slices, and returning sub-slices). That'd be a bit ugly and painful to maintain.
> 
> I'd rather avoid this. However, the `pem.rs` file is pretty much self-contained, so it can be turned into a dedicated crate, with a `no_std` compatible API.

Thanks a lot for the answer, it makes sense!



> FWIW, the @RustCrypto `pem-rfc7468` crate has full heapless `no_std` support build on a constant-time Base64 codec, implemented side-by-side with the allocating APIs.
> 
> It also supports on-the-fly Base64 decoding/encoding in constant time, which eliminates the need to perform a first pass to decode/encode to DER, allowing the DER to be parsed directly from or encoded to PEM without an intermediate buffer.
> 
> The `pkcs8` crate is already built on it, as it were (although it doesn't fully support the on-the-fly PEM APIs yet).

Thanks for the pointer, it helps a lot!
