### ISSUE TITLE
Ability to convert X25519 to Ed25519

### ISSUE THREAD

**Issue by dr-orlovsky** [jedisct1/rust-ed25519-compact#27]
You did a very fast and nice job https://github.com/jedisct1/rust-ed25519-compact/issues/18

However there is an opposite usecase: at the completion of Noise_XK handshake we know the remote Curve25519 key (used for X25519), but we need to match it against the SSH key of the node, which is Edwards25519 key. Would it be possible to have the opposite direction of the conversion?

Thank you!

**Comment by jedisct1** [comment]
Nope. The Ed25519->X25519 map can be done efficiently because X25519 only requires one coordinate. On the other hand, signatures using Ed25519 need the sign, that X25519 doesn't encode.

Maybe you can use the shared key you get out of the handshake to encrypt the Ed25519 public key?

Or do the handshake over Edwards25519. The only advantage of X25519 is that the implementation is slightly smaller than Edwards25519.

**Comment by jedisct1** [comment]
So, sorry, but that looks like a design issue in your protocol.

It's not possible to map X25519 to Ed25519 keys, at least not without additional restrictions such as choosing X25519 keys so that the sign of the corresponding Ed25519 point is constant.

**Comment by jedisct1** [comment]
Also, the standard way to encode Ed25519 secret keys is to encode a seed, that gets hashed in order to produce the actual secret.

So, recovering the seed would require breaking the hash function.

**Comment by dr-orlovsky** [comment]
Thank you for the explanation. 

I thought Curve25519 in compact encoding preserves the sign of Y coord by using one bit which remains from encoding X coord which belongs to 2^255-19 field (ie needs 255 and not 256 bits). 

Anyway I agree that authentication is better to do separately and after encryption handshake.

**Comment by tarcieri** [comment]
@dr-orlovsky that's true of compressed Edwards y-coordinates, but X25519 is just the 255-bit Montgomery-u coordinate without a sign bit (the first thing pretty much all implementations do is mask that bit off)
