### ISSUE TITLE
Compiling for release mode with debug info on wasm is unreasonably slow

### ISSUE THREAD

**Issue by ephemer** [jedisct1/rust-ed25519-compact#30]
Compiling hangs when building from my M1 MacBook Pro on macOS 13.0 with the following config. Eventually it does build if I leave it for multiple minutes, but this is an order of magnitude more than any of the other deps, so it's not a reasonable DX for us.

It's also at least an order of magnitude slower than building for, e.g. macOS arm64 with the same configuration.
Compiling without `debug = true` works fine, but I'd like to keep debug info for my Fastly configuration.

## Reproduction

```
mkdir repro && cd repro
cargo init

# replace Cargo.toml with the config below

# hangs (host: macOS arm64):
cargo build --target wasm32-wasi --release
```

## Cargo.toml

```
# Cargo.toml
[package]
name = "repro"
version = "0.1.0"
authors = []
edition = "2021"

[profile.release]
debug = true

[dependencies]
ed25519-compact = "= 2.0.4"
```

**Comment by jedisct1** [comment]
It's a known bug in the Rust compiler.

The code that generates debug info for WebAssembly is very inefficient (complexity is certainly not linear as the number of functions grows), and `field25519.rs` has many functions for it.

**Comment by jedisct1** [comment]
I don't think the debug information is used for anything on Fastly C@E, btw.
