### ISSUE TITLE
Adding a serde feature for PublicKey, SecretKey and KeyPair

### ISSUE THREAD

**Issue by raphaelahrens** [jedisct1/rust-ed25519-compact#5]
Hi,

would you be open to the idea of adding a feature for serde serialization to the crate?

**Comment by jedisct1** [comment]
As long as this is optional, and not part of the default features set, sure.

But why only these specific types? `Signature` could also be part of the game :)

**Comment by raphaelahrens** [comment]
Hi,
please see PR #7 .

I also now saw that you already had a PR #2 that was trying to add serde.
Why was #2 closed?

Greetings
